apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: resolver-pipeline
spec:
  tasks:
    - name: resolver-task
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/amisskii/git-resolver-test
        - name: revision
          value: main
        - name: pathInRepo
          value: resolver-task.yaml
